#!/bin/bash
mysqldump -h $OPENSHIFT_MYSQL_DB_HOST -P ${OPENSHIFT_MYSQL_DB_PORT:-3306} -u ${OPENSHIFT_MYSQL_DB_USERNAME:-'admin'} --password="$OPENSHIFT_MYSQL_DB_PASSWORD" $OPENSHIFT_APP_NAME  > $OPENSHIFT_DATA_DIR/mysql_bkps/`date +"%m-%d-%y-%T"`.sql

